class EmployeesController < ApplicationController

  def employee_home

    @employee = Employee.find(params[:id])
    # Employee:(1)
    # Record an order
    # TODO: functionality for approving/disapproving an order

    # Employee:(3)
    # Produce customer mailing lists
    @emails = Array.new
    clients = Client.where(is_employee: false)
    for client in clients
      if client.employee.id == @employee.id
        @emails.push(client.email)
      end
    end

    # Employee:(4)
    # Produce a list of stock suggestions for a given customer (same as client/side)
    # TODO: Make the stock suggestions a helper method

    # TODO: Add a list of past/current/pending orders
  end

  def manager_home
    # Manager:(3)
    # Obtain a sales report for a particular month
    start_date = Date.today.beginning_of_month
    end_date = Date.today
    @sales_report = Order.where(created_at: start_date..end_date) # list of orders in the month

    # Manager:(5)
    # Produce a summary listing of revenue generated by a particular stock, stock_type, or customer
    # TODO: add revenue generated by a particular stock
    # TODO: add revenue generated by a particular stock_type
    # TODO: add revenue generated by a particular customer

    # Manager:(7)
    # Determine which employee generated the most total revenue

    # Manager:(8)
    # Determine which customer generated the most total revenue
  end

end
